### ISSUE TITLE
Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by informa** [aaronshaf/react-toggle#33]
Hi just implementing react-toggle, with ES6 - import Toggle from 'react-toggle' and getting a error 
-- Cannot read property 'focus' of undefined --    appears for checkbox.focus() so looks like it can't find this.refs.input

Wondering what I am doing wrong. I basically just added <Toggle /> on the view without passing anything.

**Comment by SanthoshVijayabaskar** [comment]
I am facing the same issue,... can someone guide on why we are facing this?

**Comment by manosim** [comment]
I've just update my app to React 0.14 and I know have the same issue. 

```
"Uncaught TypeError: Cannot read property 'focus' of undefined", source: file:///Users/Manos/Projects/gitify/build/js/app.js (4691)
```

**Comment by manosim** [comment]
Okay after some debugging I got a solution for this one:

`react-toggle` requires react `0.14.3` while my app was based on `0.14.2` so there was a conflict between the two versions as you can also see at https://gist.github.com/jimfb/4faa6cbfb1ef476bd105#multiple-copies-of-react

So in order to solve the problem, I updated my package.json to require react `0.14.3`, removed `node_modules/` and then again `npm install`. Hope it helps!

**Comment by andynoelker** [comment]
@ekonstantinidis I am using React 0.14.3 and still encountering this issue.

**Comment by manosim** [comment]
Did you try to do `npm ls | grep react` so you can check whether you have more than 1 version of React installed?

**Comment by andynoelker** [comment]
I did not see more than one version of React installed. However, I completely wiped my `node_modules` directory and ran `npm install`. I had some seemingly unrelated versioning issues with other packages but once I resolved everything, react-toggle now works! Note that I am actually on `0.14.6` of React.

**Comment by tomericco** [comment]
I'm still facing this issue of loading two React versions. I'm using React 15.2.1.

**Comment by guenli** [comment]
Maybe you should add ref property to checkbox component.
such as `<input type="text" ref="myTextInput" />`

**Comment by colinramsay** [comment]
@lalexx appears to have this fixed in their branch - I wonder if they'd be prepared to make a pull request?

**Comment by slaivyn** [comment]
I also have two React version loaded at the same time because React-toggle has React as a dependency.
I suggest to set React as a **peerDependency** of React-toggle.

**Comment by ahstro** [comment]
Looks like this is fixed and merged, just not published. I'll look into publishing a new version to npm this week.

**Comment by stevenmusumeche** [comment]
this is still an issue.  did a new version get published?

**Comment by ahstro** [comment]
No, we have a few more PRs to close before publishing the next version. I've been meaning to get too it, but have had a lot on my plate the last two weeks. I'd promise to get to it next week, but I wouldn't be able to guarantee that, but I do promise to try :)

**Comment by talhatechbryx** [comment]
@ahstro 
I'm still facing this issue of loading two React versions.
